drop table if exists users;
create table if not exists users
(
    user_id  bigint generated by default as identity
        (increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1)
        primary key,
    name     varchar(20),
    username varchar(20) default null,
    email    varchar(30) default null,
    phone    varchar(50) default null,
    website  varchar(50) default null
);

insert into users(name, username, email, phone, website)
values ('Virat', 'virat', 'virat@gmail.com', '+37145684387659', 'www.virat.com');
insert into users(name, username, email, phone, website)
values ('Steve', 'steve', 'steve@gmail.com', '+377463934905943', 'www.steve.com');

select *
from users;
