drop table if exists geo;
create table if not exists geo
(
    geo_id     bigint generated by default as identity
        (increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1)
        primary key,
    address_id bigint,
    lat        double precision,
    lng        double precision,
    constraint fk_address
        foreign key (address_id)
            references public.address (address_id),
    unique (lat, lng)
);

insert into geo(address_id, lat, lng)
values (1, -37.3159, 81.1496);
insert into geo(address_id, lat, lng)
values (2, -43.9509, -34.4618);

select *
from geo;
