drop table if exists company;
create table if not exists company
(
    company_id   bigint generated by default as identity
        (increment 1 start 1 minvalue 1 maxvalue 9223372036854775807 cache 1)
        primary key,
    user_id      bigint,
    name         varchar(30),
    catch_phrase varchar(50),
    bs           varchar(50),
    constraint fk_users
        foreign key (user_id)
            references public.users (user_id)
            on delete cascade
);

-- insert into company(user_id, name, catch_phrase, bs)
-- values (1, 'Romaguera-Crona', 'Multi-layered client-server neural-net', 'harness real-time e-markets');
-- insert into company(user_id, name, catch_phrase, bs)
-- values (2, 'Deckow-Crist', 'Proactive didactic contingency', 'synergize scalable supply-chains');
--
-- select *
-- from company;
